### PR TITLE
Removed extraneous line causing mesh update fail for Repetier firmware

### PR DESCRIPTION
**Pull request by jstevej**

### CODE REVIEW

**Comment by jneilliii** [comment]
Could you test this update for me @jstevej by installing with the URL below in plugin manager > get more > ...from URL? I had inadvertently put that line in the wrong place I think.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.1.15.zip

**Comment by jstevej** [comment]
Yes, the update works for me. Thanks!

**Comment by jstevej** [comment]
I was playing around with the code in the 0.1.15 branch, and I get this error when I flip the x axis:

```
2020-08-04 17:49:54,432 - octoprint.util.comm - ERROR - Error while processing hook bedlevelvisualizer:
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/util/comm.py", line 2849, in _readline
    ret = hook(self, ret)
  File "/home/pi/OctoPrint-BedLevelVisualizer/octoprint_bedlevelvisualizer/__init__.py", line 283, in process_gcode
    z = a[2].reshape((len(x), len(y)))
ValueError: cannot reshape array of size 25 into shape (24,5)

```
I was able to fix it like this:

```
diff --git a/octoprint_bedlevelvisualizer/__init__.py b/octoprint_bedlevelvisualizer/__init__.py
index 461f68c..280a9db 100644
--- a/octoprint_bedlevelvisualizer/__init__.py
+++ b/octoprint_bedlevelvisualizer/__init__.py
@@ -206,7 +206,7 @@ class bedlevelvisualizer(octoprint.plugin.StartupPlugin,
                                        new_line.pop(0)
                                if len(new_line) > 0:
                                        if bool(self.flip_x) != self._settings.get_boolean(["flipX"]):
-                                               new_line.reverse()
+                                                new_line = [new_line[1], new_line[0], new_line[2]]
                                        self.mesh.append(new_line)

                        elif self.regex_catmull.match(line.strip()
```

Let me know if you want me to submit another pull request.

**Comment by jneilliii** [comment]
Would you mind submitting a separate PR for that against the 0.1.15 branch please? That will resolve #185, which was on my to-do list for next release. Thanks for fixing that for me, saves me some time.

**Comment by jstevej** [comment]
Will do!

**Pull request closed without merging**
