### PR TITLE
Adjustment Angle Display

### PR DESCRIPTION
**Pull request by jneilliii**

### CODE REVIEW

**Comment by LMS0815** [comment]
Thank yo for merging.

Your plugin (....settings.jinja2) is directly modifying the stored values - which is strange - instead of saving when you push the save button. 

Other developers assign/store the variables with Saving:
```
self.onSettingsBeforeSave = function() {
		self.settingsViewModel.settings.plugins.bedlevelvisualizer.screw_hub(self.screw_hub());
}

```

Loading:

```
self.onBeforeBinding = function() {
	self.screw_hub(self.settingsViewModel.settings.plugins.bedlevelvisualizer.screw_hub());
}		

```

within the GUI `..jinja2` you would only reference to` $root.screw_hub` or ` screw_hub` instead of
` $root.settingsViewModel.settings.plugins.bedlevelvisualizer.screw_hub`

As I changed all your references to this approach in **my local code**, this was conflicting with your updates and causing the behavior you described.

settingsViewModel.settings.plugins.bedlevelvisualizer.rotation

should be 

$root.rotation

and you need to save it.
self.onSettingsBeforeSave = function() {
	self.settingsViewModel.settings.plugins.bedlevelvisualizer.rotation(self.rotation());
}

I actually do not know how and when to create the KO `self.active_mesh = ko.observableArray([])`

But I strongly believe it is not needed; updating self.mesh_data would be sufficient, as you do not save it...

```
self.onDataUpdaterPluginMessage = function (plugin, mesh_data) {
	self.mesh_date(mesh_data.mesh);
	self.mesh_data_x(x_data);
	self.mesh_data_y(y_data);
	self.mesh_data_z_height(mesh_data.bed.z_max);
}

```
EDIT: Implemented within my version already.

**Comment by LMS0815** [comment]
Seems this request is broken. I'll stop bothering you.

**Comment by jneilliii** [comment]
I liked your improvements just need to have the time to fully test and tweak as needed before releasing. You wouldn't believe how many issues I deal with because of some random problem. I'll take over from here on this change but it may be a while before it's merged.

**Comment by LMS0815** [comment]
See my repository I updated 5 min ago.
I regard the current upload as  final.
I tested it on all of my systems (and development instance).

I will not post any further updates unless you request.

You probably need to download the zip as this pull request seems to be broken due to your `Closed` comment above.

**Comment by jneilliii** [comment]
Thanks. I don't think the PR was broke because of the other PR being closed. I think it's broke because of the way you are updating your repo. Typically when you commit and push from a local clone to the github repo it would be fine. Right now it's not seeing your repo correctly. Just need to re-do the PR, doing that now.

**Pull request closed without merging**
