### PR TITLE
Added mesh degrees

### PR DESCRIPTION
**Pull request by LMS0815**
No deletions (just java cleaning). 
Hope you are OK to merge now.

### CODE REVIEW

**Comment by jneilliii** [comment]
Do you anticipate a bunch more changes?

**Comment by jneilliii** [comment]
@LMS0815, just did some quick testing and there are a couple of issues that I'm seeing.  With your version, I can no longer choose the option to not store the mesh data. To reproduce, use the clear settings for the plugin in plugin manager and restart OctoPrint.  Once restarted, go into settings and uncheck box to `Save Mesh` and press Save button.  The box gets re-checked. Also, on the tab if the option is enabled to show the adjustment graph and there is no data the table shows up blank.  Would prefer it not show up at all if there is no data.  From what I can tell, it looks like your improvements only work with stored mesh data (Save Mesh is enabled). Would be better if this worked with both Save Mesh checked or unchecked the way the surface graph does.

**Comment by LMS0815** [comment]
I'll probably had some leftovers  from my old version. Should working now,

**Comment by LMS0815** [comment]
Kindly advice which self.mesh?!? to use for non stored functionality. Changing it should not be an issue as the mesh is provided as template parameter.

**Comment by jneilliii** [comment]
So because the graph is displayed using the information passed back to the client side via onDataUpdaterPluginMessage callback there is no observableArray currently storing a "current mesh", so it would probably have to be added. Maybe using something like `self.current_mesh = ko.observableArray([])` or `self.active_mesh = ko.observableArray([])`. Then in onBeforeBinding if save_mesh() is true assign the stored_mesh to the active_mesh? If you have other thoughts let's discuss.

I was wondering something though and I'm always looking to improve my programming skills if there is logic behind it. I notice you assigned all your observables you added and are updating them in onBeforeBinding and then updating the settings side in onSettingsBeforeSave. Is that for convenience so you don't have to type `settingsViewModel.settings.plugins.bedlevelvisualizer.` in front of the observables in the HTML side of the view model or for some other reason?

**Comment by jneilliii** [comment]
Closing this one in favor of PR #200 to different branch.  Keep making your changes in your Master branch and it will update the PR automatically.

**Comment by LMS0815** [comment]
Thank yo for merging.

Your plugin (....settings.jinja2) is directly modifying the stored values - which is strange - instead of saving when you push the save button. 

Other developers assign/store the variables with Saving:
```
self.onSettingsBeforeSave = function() {
		self.settingsViewModel.settings.plugins.bedlevelvisualizer.screw_hub(self.screw_hub());
}

```

Loading:

```
self.onBeforeBinding = function() {
	self.screw_hub(self.settingsViewModel.settings.plugins.bedlevelvisualizer.screw_hub());
}		

```

within the GUI `..jinja2` you would only reference to` $root.screw_hub` or ` screw_hub` instead of
` $root.settingsViewModel.settings.plugins.bedlevelvisualizer.screw_hub`

As I changed all your references to this approach in **my local code**, this was conflicting with your updates and causing the behavior you described.

settingsViewModel.settings.plugins.bedlevelvisualizer.rotation

should be 

$root.rotation

and you need to save it.
self.onSettingsBeforeSave = function() {
	self.settingsViewModel.settings.plugins.bedlevelvisualizer.rotation(self.rotation());
}

I actually do not know how and when to create the KO `self.active_mesh = ko.observableArray([])`

But I strongly believe it is not needed; updating self.mesh_data would be sufficient, as you do not save it...

```
self.onDataUpdaterPluginMessage = function (plugin, mesh_data) {
	self.mesh_date(mesh_data.mesh)
	self.mesh_data_x(,x_data)
	self.mesh_data_y(y_data)
	self.mesh_data_z_height(mesh_data.bed.z_max)  //?!?!
}

```

**Pull request closed without merging**
