### PR TITLE
Improved look & feel + support of imperial settings

### PR DESCRIPTION
**Pull request by LMS0815**

### CODE REVIEW

**Comment by jneilliii** [comment]
@LMS0815, there still appears to be conflicts. I assume you didn't update your master from the latest version, but I'm not familiar enough with git to know for sure.

**Comment by LMS0815** [comment]
You  need to accept my changes and allow modifying the master.

> Only those with write access to this repository can merge pull requests.

I would understand if you do not like it.
But I do not want to publish a forked version...

**Comment by LMS0815** [comment]
Try downloading my version from git (as zip) and give it a try.

**Comment by jneilliii** [comment]
Sorry, I assumed you could update your branch by merging my changes to master into yours, but I just cherry picked your changes and manually merged into my 0.1.13 branch.  Please test using this URL from plugin manager.  My branch had a ton of changes between versions so it took a little while.

https://github.com/jneilliii/OctoPrint-BedLevelVisualizer/archive/0.1.13.zip

**Comment by LMS0815** [comment]
Seems you (and me) provided improvements at the same time.

**Pull request closed without merging**
