### PR TITLE
0.1.13

### LINKED ISSUE #142: Add output in degrees
Would be very helpful to add the output in degrees for the bed leveling M3 screws, like in this sheet: https://docs.google.com/spreadsheets/d/1AC3NHQXZbEj1rc0tZtuaRyycx2clcZNnR04FSibEA04/edit?usp=sharing

### LINKED ISSUE #208: Bed Visualizer causes high network load
When I have this plugin enabled, there is a constant 2Mbps+ data flow on my network, which goes away only if I close the OctoPrint tab, or if I disable Bed Visualizer. I suspect this plugin is somehow keeping the webcam stream open constantly, whether the Control page is open or not. "Show webcam while processing" is disabled.

Bed Visualizer 0.1.12
OctoPrint 1.4.0 running on OctoPi 0.15.1

### PR DESCRIPTION
**Pull request by jneilliii**
Made webcam image not load when that option isn't enabled and only while processing, resolves #208 
Screw based adjustment degrees, thanks to @LMS0815, resolves #142

### CODE REVIEW

**Comment by LMS0815** [comment]
Hi @jneilliii thank you for merging. Seems you missed my most advanced feature the "Screw visualization". 
Anmerkung 2020-03-31 111242

Was this by purposes?

**Comment by jneilliii** [comment]
Yes, there was some weird inconsistencies that I couldn't figure out why it was happening where some numbers when hovering over would not display the screw. It's there, just set to not visible for now until I had some time to test/ debug.

**Comment by LMS0815** [comment]
Ah! Hoovering any number (despite zero) is updating the KO value which is used to trigger visibility and the image. Hope you'll find the issue soon. :)

**Comment by jneilliii** [comment]
Yeah, it was odd. It would hide when I was hovering over non-zero numbers. I'd I cam reproduce I'll let you know.

**Comment by LMS0815** [comment]
The only thing I can think of is a value type issue.

Try:
`event: { mouseover: function(item){$root.turn(parseFloat(item));},mouseout: function(){$root.turn(0);}},
`

**Pull request merged**
